version: '3'
services:
  metabase:
    image: metabase/metabase:latest
    ports:
     - "3300:3000"
    volumes:
     - ./metabase-data:/metabase-data
    environment:
     - "MB_DB_FILE=/metabase-data/metabase.db"
